[package]
name = "argent-genesis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
argent-artifact = { workspace = true }
argent-runtime = { workspace = true }
kaspa-consensus-core = { workspace = true }
kaspa-txscript = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
silverscript-abi = { workspace = true }
thiserror = { workspace = true }
